### ISSUE TITLE
Add integration to have LocalLifecycleOwner/LocalSavedStateRegistryOwner/LocalViewModelStoreOwner at each Composable level

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack-compose-integration#15]
Certain Jetpack libraries such as AndroidX Camera require integration against lifecycleOwners and whatnot, but without setting up a LocalLifecycleOwner, that would use the Activity, and would not respect the removal from the composition.

The problem is that while service creation and activation state is tracked, `onStart/onStop` are not. However, we can easily ask for `LifecycleOwner` and observe it ourselves to get this information.

Also, enabling scoped services is completely optional, it's only enabled when `setScopedServices()` is set to a value that is meaningful. But this makes it tricky to store the ViewModelStoreOwner (although retained objects were added specifically with this feature in mind in the future, same for its `Bundleable` support).

However, there is no way around this, this must be implemented at some point, as while sure, you can show a Composable as a screen, but you won't be able to interop that easily with AndroidX -- which harms the adoption of this library.

**Comment by matejdro** [comment]
Is there a point in adding `LocalViewModelStoreOwner`? I thought "the simple stack way" is to use scoped services, not AndroidX ViewModel

**Comment by matejdro** [comment]
As for `LocalSaveableStateRegistry`, it seems that `SaveableStateHolder`already takes care of this.

**Comment by Zhuinden** [comment]
It is true that Simple-Stack by default prefers ScopedServices, the problem is that AndroidX libraries such as CameraX relies on the enclosing container to have a meaningful ViewModelStoreOwner. 

For our general cases, we've still been using Fragments as the host of the ComposeView, but some Google integrations do just say "yeah lemme grab a ViewModel", and that shouldn't be scoped to the Activity. 🤔

So it's more so a Compose integration requirement, not a Simple-Stack requirement.

**Comment by Zhuinden** [comment]
@matejdro I forgot to say, thank you for the contribution! I've released the latest changes in 0.10.0. 

In the end, we didn't actually introduce a lot of significant breaking changes, and this solves some very long-lasting problems. Now all I need to do is think of a good way to handle https://github.com/Zhuinden/simple-stack/issues/259 to handle `android:enableOnBackInvokedCallback` so that exiting the app will that fancy gesture animation, but I'll actually try to tackle that sometime next week. I don't like having to call the deprecated `onBackPressed`. 😅
