### ISSUE TITLE
Animations are not correct in the example-dogs

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack-compose-integration#19]
After merging https://github.com/Zhuinden/simple-stack-compose-integration/pull/17, the animation between screens when clicking a dog isn't correct, there is no translation animation happening.

Theoretically the default transition should be a horizontal segue animation.

@matejdro please check what's going on if you can, as this blocks a new version release using the new ComposeStateChanger.

---

Interesting to note that it DOES work in `example-simple`.

**Comment by Zhuinden** [comment]
The other alternative would be to revert the #17 changes and then use the #18 code in the old state changer, but one of the primary criticisms even back in the day for this lib was the lack of support for AnimatedContent - even though it was technically safer to use the graphicsLayer-based anims. Alas, we'll see how that goes, we can do anything we want unless it's made 1.0 😅

**Comment by matejdro** [comment]
Just for the clarification, #17 does NOT use AnimatedContent. It uses same Modifier animations as before, just in refactored form.

**Comment by Zhuinden** [comment]
@matejdro oh, that's better news. But I'm still not sure why the dogs are no longer animated during screen transitions. Maybe it has something to do with how Coil works?
