### ISSUE TITLE
Remove Modifier from DefaultComposeKey

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack-compose-integration#21]
It is not clear what this modifier would be used for and relying on it can cause trouble, since screens do not need to use it, as demonstrated in in #20. I think it would be helpful if this Modifier would be altogether removed to reduce confusion.

**Comment by Zhuinden** [comment]
Theoretically it is trying to mimic this thing: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-compose/src/main/java/androidx/navigation/compose/NavHost.kt;l=94?q=navhost

But if there's no good use for it, I can remove it.

**Comment by matejdro** [comment]
NavHost would actually be more akin to the `ComposeStateChanger.RenderScreen` which has (and it should have) a Modiifer.

Navigation compose's closest analogy to the `DefaultComposeKey` would be `NavGraphBuilder.composable`: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-compose/src/main/java/androidx/navigation/compose/NavGraphBuilder.kt;l=39, which has no Modifier.
