### ISSUE TITLE
Nested Navigation + Scoped Services

### ISSUE THREAD

**Issue by lcszc** [Zhuinden/simple-stack-compose-integration#32]
Hey there,

I've been playing around with this compose integration version of Simple Stack and I was implementing a nested navigation like this:

```kotlin
@Immutable
@Parcelize
data object RootKey: ComposeKey() {
    operator fun invoke() = this

    @Composable
    override fun ScreenComposable(modifier: Modifier) {
        ComposeNavigator {
              createBackstack(
                  History.of(FirstNestedKey()),
                  scopedServices = DefaultServiceProvider()
              )
        }
    }
}
```

and `RootKey` set up its scoped services:

```kotlin
override fun bindServices(serviceBinder: ServiceBinder) {
        with(serviceBinder) {
            val service = Service()
            add(service)
        }
    }
```

Can the nested keys access the service instance above when looking up? The idea is that the parent's service can be accessed by its children because this service will have its lifecycle tied to this key, like when you have a login/signup flow. You want their containers (services/managers/etc) to get GCed after going through them.

Does it make sense and are the nested screens supposed to support this kind of behavior?

**Note**: 
 - currently doing `get()`, `lookup()` on `FirstNestedKey` will throw.
 - We can also use global services for it and put this service there, but I'm not sure if this global service will be feature-scoped (key) or app-scoped. If we already have the default app-scoped global services then you can't build a new global service on top of the existing one so you would need to do it manually (app's service + feature services).

**Comment by Zhuinden** [comment]
Hey hey, I haven't been seeing activity on this repository in a while and I'm still using fragments in real projects, BUT this is effectively a by-product of https://github.com/Zhuinden/simple-stack-compose-integration/issues/28 being an open question.

If the nested screen did a lookup of an existing `LocalBackstack`  and used `backstack.setParentServices()` if it's non-null, then the nested child would be able to look up services.

I checked the code and it seems I merely theorized the option, but it was not implemented. I do think it is most likely something that should happen automatically though.

**Comment by Zhuinden** [comment]
On second thought, `LocalBackstack` is not guaranteed to be set.

`ComposeNavigatorInitializer` requires a field called `parentServices: Backstack? = null` and that can be set to allow lookup across a hierarchy, imo.

**Comment by Zhuinden** [comment]
Should be fixed in 0.13.0 if you pass the parent backstack to `ComposeNavigator` or `rememberBackstack` https://github.com/Zhuinden/simple-stack-compose-integration/commit/4b316c122fe808151e49d778da3298b074f2bc7c

**Comment by lcszc** [comment]
Thanks @Zhuinden 

That's great. I'm glad this was an easy fix. I'm also more of a Fragment-based user but wanted to try out how fast it is to move with Compose while having full navigation control and all the simple setup this library offers.

Thank you!

**Comment by Zhuinden** [comment]
The fact that this was already mostly implemented in the core lib made it much easier to do, that one was up for [question] [design required] and took a bit to implement at the time... https://github.com/Zhuinden/simple-stack/issues/239#issuecomment-1612443305

Anyway, if this solved your issue, good 😁
