### ISSUE TITLE
Dependency in readme has a typo

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack-compose-integration#5]
Readme states 

```implementation("com.github.Zhuinden.simple-stack-compose-integration:0.2.0")```

But it should state

```implementation("com.github.Zhuinden:simple-stack-compose-integration:0.2.0")```

**Comment by Zhuinden** [comment]
Valid point I probably had that because of the "core/services" split and copied incorrectly, fixed in https://github.com/Zhuinden/simple-stack-compose-integration/commit/8d10cb00406b3b73bb05602ed0fe4f623f2aa4ed
