### ISSUE TITLE
Failed to resolve: com.github.Zhuinden:simple-stack-compose-integration:0.3.1

### ISSUE THREAD

**Issue by pandasys** [Zhuinden/simple-stack-compose-integration#8]
0.3.0 is resolved but can't download 0.3.1. Also, there's a typo in your README that I happened to copy/paste - implementation("com.github.Zhuinden.simple-stack-compose-integration:0.3.1") - note the '.' instead of ':' after Zhuinden.

**Comment by Zhuinden** [comment]
Hmm, Jitpack claims that the artifacts are available at

```
com.github.Zhuinden.simple-stack-compose-integration:services:0.3.1
com.github.Zhuinden.simple-stack-compose-integration:core:0.3.1
```

this does mean that there should be a `:` instead of a `.`, so

```
com.github.Zhuinden:simple-stack-compose-integration:0.3.1
```

But it *is* hosted on Jitpack. 🤔  I've updated the readme, but I don't see why it shouldn't be available under the correct coordinates

**Comment by pandasys** [comment]
I cleaned, deleted caches, etc... and it's resolving now. Thanks for looking into it.
